version: '3.7'

services:
  php:
    image: essangthegreat/stamp-user-service:1.0
    container_name: stamp_user_service
    restart: always
    ports:
      - 80:80
    environment:
      - APP_KEY=base64:34xWqM9LGJoe3bX60c2IqwsWkQ6ETFdHWhtheGMekJ8=
      - APP_ENV=http://localhost:8001
      - APP_DOCKER_INTERNAL=http://host.docker.internal:8001
      - APP_DEBUG=true
      - APP_TIMEZONE=UTC
      - DB_PORT=3306
      - DB_HOST=stamp_users_mysql
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=sync
    # volumes:
    #   - ./src:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: stamp_user_db
    restart: always
    hostname: stamp_users_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}

networks:
  default:
